services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev -- --host 0.0.0.0
    networks:
      - websocket-net

networks:
  websocket-net:
    external: true
    name: websocket-net

volumes:
  node_modules: